### ISSUE TITLE
Web support 

### ISSUE THREAD

**Issue by devZakariya** [GiancarloCode/form_bloc#130] opened 2020-07-16 08:36 UTC
Hey 
please why there is no more web support for the flutter_form_bloc ?

**Comment by JohnGalt1717** [comment] 2020-07-16 17:16
I'm having the same problem. No errors until you try and put a textbloc on and then it blows up.  Which seems odd that there is platform specific code in a textbloc

**Comment by GiancarloCode** [comment] 2020-07-16 17:26
Hello, the web support has not changed, and I have only updated dependencies in the latest version, 

Please provide a screenshot, log if there is any error, and code snippet to reproduce the error.

**Comment by JohnGalt1717** [comment] 2020-07-16 18:04
Add any textfieldblocbuilder to a new correctly setup project:

TextFieldBlocBuilder(
                                  textFieldBloc: bloc.lastOrCompanyName,
                                  decoration: InputDecoration(
                                    labelText: "Company"
                                  ),
                                )

Run.


════════ Exception caught by widgets library ═══════════════════════════════════
Unsupported operation: Platform._operatingSystem
The relevant error-causing widget was
    TextFieldBlocBuilder 
lib\…\edit\contact.page.dart:100
════════════════════════════════════════════════════════════════════════════════

If you look here: https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/lib/src/text_field_bloc_builder.dart

Line 831:  if (Platform.isAndroid || Platform.isIOS) {

this will always fail on web until this is fixed and these return properly: https://github.com/flutter/flutter/issues/50845

But even then, this logic won't get you what is intended because it will still return true for isAndroid/isIOS on the browsers on those devices.  It should have the logic inverted so that it tests "isWeb" first and returns if true the web version, and then, if not isWeb, it should test the platform if necessary (I doubt it is right now)

This throws on all Builders.

Hope that helps.

**Comment by GiancarloCode** [comment] 2020-07-16 19:07
@JohnGalt1717  I see, thanks, I did not know this getters did not work, I will fix it in a few hours
I will use `kIsWeb` first, and then the same logic
they had been changed to support desktop,

**Comment by JohnGalt1717** [comment] 2020-07-16 19:10
Great!

You might consider using the platform interface system to split out the logic for each platform. That would clean up the code by separating the logic based on each platform the user wants to add as a plugin, and would also allow new platforms to be added more easily going forward. That's probably a larger migration than just a bug fix for right now though.

**Comment by GiancarloCode** [comment] 2020-07-16 19:42
Fixed in
```dart
  flutter_form_bloc: ^0.15.1
```

@JohnGalt1717 thank you, PRs are welcome

**Closed** 2020-07-18 15:07 UTC
